import { Router } from "express";
import { z } from "zod";
import * as student from "../controllers/studentController";
import { authenticate, authorize } from "../middleware/auth";
import { validateRequest } from "../middleware/error";
import { submitLimiter } from "../middleware/rateLimit";
import { integrityEventSchema } from "@testora-platform/shared";

const answersSchema = z.object({ answers: z.array(z.object({ questionId: z.string(), answer: z.any(), answered: z.boolean().optional() })) });
const aiFeedbackSchema = z.object({ type: z.enum(["WRITING", "SPEAKING"]), text: z.string().trim().min(20).max(12000), prompt: z.string().trim().max(2000).optional(), attemptId: z.string().min(1).max(64).optional(), examId: z.string().min(1).max(64).optional() });
const router = Router();
router.use(authenticate, authorize("STUDENT"));
router.get("/dashboard", student.dashboard);
router.get("/exams", student.listExams);
router.get("/practice", student.listPracticeExams);
router.get("/practice/adaptive", student.adaptivePractice);
router.get("/practice/profile", student.learningProfile);
router.get("/practice/summary", student.sectionalSummary);
router.get("/exams/:id", student.getExam);
router.post("/exams/:id/start", student.startExam);
router.get("/attempts/:id", student.getAttempt);
router.patch("/attempts/:id/answers", validateRequest(answersSchema as never), student.saveAnswers);
router.post("/attempts/:id/integrity-event", validateRequest(integrityEventSchema as never), student.integrityEvent);
router.post("/attempts/:id/submit", submitLimiter, student.submitAttempt);
router.post("/attempts/:id/ai-check", submitLimiter, student.aiCheckAttempt);
router.get("/assignments", student.listAssignments);
router.get("/assignments/:id", student.getAssignment);
router.post("/assignments/:id/submit", submitLimiter, student.submitAssignment);
router.get("/results", student.listResults);
router.get("/results/:id", student.getResult);
router.get("/progress", student.progress);
router.get("/progress/analytics", student.progressAnalytics);
router.get("/feedback", student.feedback);
router.post("/feedback/ai", submitLimiter, validateRequest(aiFeedbackSchema as never), student.aiFeedback);
router.get("/feedback/ai/history", student.aiFeedbackHistory);
router.get("/leaderboard", student.leaderboard);
router.get("/notifications", student.listNotifications);
router.patch("/notifications/:id/read", student.markRead);
router.post("/notifications/read-all", student.markAllRead);
export default router;
