import { Request, Response } from "express";
import * as userService from "../services/userService";
import * as teacherService from "../services/teacherService";
import * as reportService from "../services/reportService";
import * as questionBankService from "../services/questionBankService";
import { ApiError, asyncHandler } from "../utils/helpers";
import { studentIdsOfTeacher } from "../services/userService";

export const dashboard = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); res.json({ success: true, message: "Teacher dashboard", data: await teacherService.teacherDashboard(req.user.id) }); });
export const listStudents = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); const ids = await studentIdsOfTeacher(req.user.id); const result = await userService.listUsers("STUDENT", queryOf(req), { teacherId: req.user.id }); const data = result.data.map((s) => { const r = s as { id: string }; return { ...(s as Record<string, unknown>), accessible: ids.some((i) => String(i) === r.id) }; }); res.json({ success: true, message: "My students", data, pagination: { page: result.page, limit: result.limit, total: result.total, pages: result.pages } }); });
export const getStudent = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); if (!(await isStudentAccessible(req.user.id, String(req.params.id)))) throw new ApiError(403, "You do not have access to this student"); res.json({ success: true, message: "Student", data: await userService.getUserById(String(req.params.id), "STUDENT") }); });
export const createStudent = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); res.status(201).json({ success: true, message: "Student created", data: await userService.createUser({ ...req.body, role: "STUDENT", teacherId: req.user.id }, { id: req.user.id, role: req.user.role }, req.ip || null) }); });
export const updateStudent = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); if (!(await isStudentAccessible(req.user.id, String(req.params.id)))) throw new ApiError(403, "You do not have access to this student"); res.json({ success: true, message: "Student updated", data: await userService.updateUser(String(req.params.id), req.body, { id: req.user.id, role: req.user.role }, req.ip || null) }); });
export const setStudentStatus = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); if (!(await isStudentAccessible(req.user.id, String(req.params.id)))) throw new ApiError(403, "You do not have access to this student"); res.json({ success: true, message: "Student status updated", data: await userService.updateUserStatus(String(req.params.id), req.body.status, { id: req.user.id, role: req.user.role }, req.ip || null) }); });
export const resetStudentPassword = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); if (!(await isStudentAccessible(req.user.id, String(req.params.id)))) throw new ApiError(403, "You do not have access to this student"); await userService.resetPasswordByAdmin(String(req.params.id), req.body.password, { id: req.user.id, role: req.user.role }, req.ip || null); res.json({ success: true, message: "Password reset" }); });
export const listBatches = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); res.json({ success: true, message: "Batches", data: await teacherService.listBatches(req.user.id, req.query.courseType as string | undefined) }); });
export const createBatch = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); res.status(201).json({ success: true, message: "Batch created", data: await teacherService.createBatch(req.body, req.user.id) }); });
export const updateBatch = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); res.json({ success: true, message: "Batch updated", data: await teacherService.updateBatch(String(req.params.id), req.body, req.user.id) }); });
export const addStudentsToBatch = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); await teacherService.addStudentsToBatch(String(req.params.id), req.body.studentIds, req.user.id); res.json({ success: true, message: "Students added to batch" }); });
export const reports = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); res.json({ success: true, message: "Teacher report", data: await reportService.teacherReport(req.user.id) }); });
export const exportQuestionBank = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); const format = req.query.format === "xlsx" ? "xlsx" : "csv"; const file = await questionBankService.exportQuestions(req.user.id, format); res.setHeader("Content-Type", file.contentType); res.setHeader("Content-Disposition", `attachment; filename="${file.filename}"`); res.send(file.buffer); });
export const importQuestionBank = asyncHandler(async (req: Request, res: Response) => { if (!req.user) throw new ApiError(401, "Authentication required"); const file = req.file as Express.Multer.File | undefined; if (!file) throw new ApiError(400, "CSV or XLSX file is required"); const result = await questionBankService.importQuestions(req.user.id, file); if (result.failed) return res.status(400).json({ success: false, message: "Question bank import failed validation", data: result }); res.status(201).json({ success: true, message: `${result.created} questions imported`, data: result }); });
async function isStudentAccessible(teacherId: string, studentId: string): Promise<boolean> { return userService.verifyTeacherOwnership(teacherId, studentId); }
function queryOf(req: Request): Record<string, string> { return { page: String(req.query.page || 1), limit: String(req.query.limit || 10), search: (req.query.search as string) || "", sort: (req.query.sort as string) || "-createdAt", status: (req.query.status as string) || "" }; }
